# Generated by Django 3.1.1 on 2020-11-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('phone', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('subject', models.TextField()),
                ('day', models.TextField()),
                ('hour', models.TextField()),
            ],
        ),
    ]
