# Generated by Django 3.1.1 on 2020-11-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='day',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
