# Generated by Django 3.1.1 on 2020-11-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20201118_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='hour',
        ),
    ]
