# Generated by Django 3.1.1 on 2020-11-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20201124_1519'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('day', 'hour')},
        ),
    ]
